---

- name: ping
  hosts: Wordpress
  become: yes
  tasks:
    - name: ping_machine_cible
      ping:

    # PHP
    - name: Add the ondrej PHP PPA
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install php
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-fpm
        - php-mysql
        - php-xml

    - name: Remove apache2
      package:
        name: apache2
        state: absent

    - name: Install MySQL
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - python-mysqldb

#    - name: Remove anonymous users
#      mysql_user:
#        name: ""
#        state: absent

#    - name: Remove anonymous users
#      mysql_user:
#        name: ""
#        state: absent
